
services:
  postgres:
    image: postgres:15
    container_name: ledger-db
    restart: always
    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
volumes:
  postgres_data:

